language: node_js
node_js: stable
cache: npm

script:
  - echo "Running tests against $(node -v) ..."
  - npm run build
  - npm run build:mini
  - npm test

deploy:
  provider: npm
  email: moohng@126.com
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    tags: true


