language: node_js
node_js: stable
cache: npm

script:
  - echo "Running tests against $(node -v) ..."
  - npm run lib
  - npm run dist
  - npm test

deploy:
  provider: npm
  email: moohng@126.com
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    tags: true

after_success:
  - bash <(curl -s https://codecov.io/bash)
